import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";

import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "AI Mock Interview App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ['latin'] });

const clerkPublishableKey =
  process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY ||
  "pk_test_Y2xlcmstcHVibGlzaGFibGUta2V5LWZhbGxiYWNrJG";

if (!process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY && typeof window !== "undefined") {
  console.warn(
    "[Clerk Warning]: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY is missing in environment variables. Please configure NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY in Vercel project settings."
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={clerkPublishableKey}>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={outfit.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ConvexClientProvider>
              {children}
              <Toaster />
            </ConvexClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
